# [Messages] MODELS.PY - Copyright (c) 2016 - Sean Bailey - All Rights Reserved
# Powered by Django (https://www.djangoproject.com/) - Not endorsed by Django
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Django Imports
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Other Imports
import uuid
from . import identifier as ident

# Chat Room Class
# Represents the database model that each chatroom, public or private,
# must adopt.
class ChatRoom(models.Model):

    # The name can be changed at anytime by the rooms moderators.
    # Does not have to be unique, and should not be use as the primary
    # key.
    name = models.CharField(max_length=32)

    # This identifier is a unique 7 character base64 string, that is
    # generated by identifier.py. It can be changed to any unique string
    # of base64 characters by premium moderators in public chats. The
    # identifier is also used as the absolute url of any chat when
    # sluggified. For example: https://cometchat.cc/custom-identifier
    identifier = models.CharField(
        unique=True,
        primary_key=True,
        max_length=20,
        default=ident.generate,
    )

    # Self explanatory
    date_created = models.DateTimeField(default=timezone.now)

    # Should the chat room be accesssible to the public? If true, then
    # anyone with the absolute url can join the chat room.
    is_public = models.BooleanField(default=False)

    # Creator's have elavated permissions compared to moderators.
    creator = models.UUIDField(default=uuid.uuid4)

    # TODO Add a dict for moderators

    def __unicode__(self):
        return str(self.name)

    @models.permalink
    def get_absolute_url(self):
        return "/messages/%s" % str(self.identifier)
